# Generated by Django 6.0.3 on 2026-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guest_valid_until',
            field=models.DateTimeField(blank=True, help_text='Дата истечения доступа для гостей', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('guest', 'Временный гость')], default='employee', help_text='Тип пользователя', max_length=20),
        ),
    ]
