# Generated by Django 6.0.3 on 2026-03-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_guest_valid_until_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Указывает активен ли пользователь'),
        ),
    ]
