# Generated by Django 6.0.3 on 2026-03-24 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0005_guestpass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Созданный аккаунт пользователя для гостя (если это временный сотрудник)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_pass', to=settings.AUTH_USER_MODEL),
        ),
    ]
