# Generated by Django 6.0.3 on 2026-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaner', '0006_guestpass_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpass',
            name='guest_patronymic',
            field=models.CharField(blank=True, default='', help_text='Отчество гостя', max_length=50),
        ),
        migrations.AddField(
            model_name='guestpass',
            name='guest_surname',
            field=models.CharField(default='', help_text='Фамилия гостя', max_length=50),
        ),
        migrations.AlterField(
            model_name='guestpass',
            name='guest_name',
            field=models.CharField(default='', help_text='Имя гостя', max_length=50),
        ),
    ]
